//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMyLibraryWindowsFormsApp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposits
    {
        public int DepositId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<double> Fine { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
